allowBuilds:
  '@dargmuesli/nuxt-vio': false
  '@firebase/util': false
  '@parcel/watcher': false
  '@sentry-internal/node-cpu-profiler': false
  '@sentry/cli': false
  esbuild: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
overrides:
  parse5-parser-stream: 8.0.0
packages:
  - src
  - tests
