allowBuilds:
  '@dargmuesli/nuxt-vio': false
  '@firebase/util': false
  '@parcel/watcher': false
  '@sentry-internal/node-cpu-profiler': false
  '@sentry/cli': false
  '@sentry/node-cpu-profiler': false
  esbuild: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@nuxtjs/i18n@10.5.0'
packages:
  - src
  - tests
