name: "Browserslist: Regex"

permissions: {}

on:
  schedule:
    - cron: "0 0 * * 2" # Every Tuesday at 00:00 AM UTC on the default branch
  workflow_dispatch:

jobs:
  browserslist-regex:
    uses: dargmuesli/github-actions/.github/workflows/browserslist-regex.yml@121d4c605f0d1d6eeca65ad8026ac09d7594fe76 # 5.9.8
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      DIRECTORY: src/
      OUTPUT_PATH: app/supportedBrowsers.js
      UBUNTU_DEPENDENCIES: mkcert
      UBUNTU_REPOSITORIES: universe
