name: "Browserslist: Regex"

permissions: {}

on:
  schedule:
    - cron: "0 0 * * 2" # Every Tuesday at 00:00 AM UTC on the default branch
  workflow_dispatch:

jobs:
  browserslist-regex:
    uses: dargmuesli/github-actions/.github/workflows/browserslist-regex.yml@2fb9bdae5c8ce52ea7f9546d1ba22c34921246de # 5.1.3
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      DIRECTORY: src/
      OUTPUT_PATH: app/supportedBrowsers.js
      UBUNTU_DEPENDENCIES: mkcert
      UBUNTU_REPOSITORIES: universe
